### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/doubter#2]
- [x] add glob pattern support
- [x] support files located at the outside of `CARGO_MANIFEST_DIR` (#9)
- [x] extract code blocks in Markdown file
- [x] ~~add exclude pattern support~~
